# Generated by Django 2.2.3 on 2019-07-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_mng', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'permissions': (('can_mark_returned', 'Can mark rent as returned'), ('can_show_week', 'Can show week view'))},
        ),
    ]
