# Generated by Django 2.2.3 on 2019-07-25 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_mng', '0002_rent_rented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rent',
            name='to_date',
            field=models.DateField(),
        ),
    ]
