# Generated by Django 2.2.3 on 2019-08-17 16:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_mng', '0002_auto_20190817_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='MileageChecks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_check', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('checked', models.BooleanField(default=False)),
                ('checked_mileage', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet_mng.Vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
