# Generated by Django 2.2.3 on 2019-07-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_mng', '0002_auto_20190726_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renter',
            name='name',
        ),
        migrations.AddField(
            model_name='renter',
            name='first_name',
            field=models.CharField(blank=True, max_length=193),
        ),
        migrations.AddField(
            model_name='renter',
            name='last_name',
            field=models.CharField(default='Noname', max_length=193),
            preserve_default=False,
        ),
    ]
