# Generated by Django 2.2.3 on 2019-08-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_mng', '0003_auto_20190730_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
