# Generated by Django 2.2.3 on 2019-07-25 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_mng', '0003_auto_20190725_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'permissions': (('can_mark_returned', 'Set vehicle as returned'),)},
        ),
    ]
