# Generated by Django 2.2.3 on 2019-07-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_mng', '0004_auto_20190725_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'permissions': (('can_mark_returned', 'Set vehicle as returned'), ('can_show_week', 'Show week view'))},
        ),
    ]
