# Generated by Django 2.2.3 on 2019-08-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_mng', '0005_auto_20190803_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='chekup',
            new_name='checkup',
        ),
    ]
