# Generated by Django 2.2.3 on 2019-08-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_mng', '0006_auto_20190803_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
    ]
