# Generated by Django 2.2.3 on 2019-08-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_mng', '0007_auto_20190804_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='insurance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
